CREATE DATABASE EMPLOYEE_MANAGEMENT;
USE EMPLOYEE_MANAGEMENT;

DROP TABLE DEPARTMENTS;

CREATE TABLE DEPARTMENTS (DEPARTMENT_ID INT PRIMARY KEY, NAME VARCHAR(50) NOT NULL);

INSERT INTO DEPARTMENTS VALUES(1,'HR'),(2,'IT'),(3,'TESTING'),(4,'DEVELOPER'),(5,'MANAGEMENT');

SELECT * FROM DEPARTMENTS;

DROP TABLE EMPLOYEES;
CREATE TABLE EMPLOYEES (EMPLOYEE_ID INT PRIMARY KEY,NAME VARCHAR(100),AGE INT,GENDER VARCHAR(50),SALARY INT,DEPARTMENT_ID INT);

INSERT INTO EMPLOYEES VALUES(01,'RAVI',27,'MALE',50000,1),
(02,'YUVA',23,'MALE',57000,2),
(03,'GOMATHI',20,'FEMALE',60000,3),
(04,'SINDHU',22,'FEMALE',55000,4),
(05,'SHARMI',21,'FEMALE',59000,5);

SELECT * FROM EMPLOYEES;
DROP TABLE PROJECTS;
CREATE TABLE PROJECTS (ID INT,NAME VARCHAR(100),BUDGET INT);

INSERT INTO PROJECTS VALUES('1001','APP DEVELOPER',350000),
('1002','WEB DEVELOPER',400000),
('1003','DATA ANALYTIC',200000),
('1004','FULLSTACK DEVELOPER',100000),
('1005','SOFTWARE TESTING',300000);

SELECT * FROM PROJECTS;

CREATE TABLE EMPLOYEE_PROJECTS (EMPLOYEE_ID INT PRIMARY KEY,PROJECT_ID VARCHAR(200));

INSERT INTO EMPLOYEE_PROJECTS VALUES(01,'P01'),(02,'P02'),(03,'P03'),(04,'P04'),(05,'P05');

SELECT * FROM EMPLOYEE_PROJECTS;
DROP TABLE ATTENDANCE;
CREATE TABLE ATTENDANCE (EMPLOYEE_ID INT PRIMARY KEY,DATE INT ,STATUS varchar(50));

INSERT INTO ATTENDANCE VALUES(01, 2024-10-06, 'PRESENT'),
(02, 2024-10-06, 'ABSENT'),
(03, 2024-10-06, 'PRESENT'),
(04, 2024-10-06, 'ABSENT'),
(05, 2024-10-06, 'ABSENT');

SELECT * FROM ATTENDANCE;

#EX2
SELECT Employees.name AS EMPLOYEE_NAME,DEPARTMENTS.NAME AS DEPARTMENT_NAME 
FROM Employees JOIN departments ON Employees.DEPARTMENT_id = DEPARTMENTS.DEPARTMENT_ID WHERE DEPARTMENTS.NAME ='IT';

#EX3
SELECT PROJECTS.Name AS PROJECT_Name,budget FROM Projects WHERE budget > 50000;

#EX4
SELECT EMPLOYEES.NAME AS EMPLOYEE_NAME, PROJECTS.NAME AS PROJECT_NAME
FROM EMPLOYEES JOIN PROJECTS ON EMPLOYEES.EMPLOYEE_ID = PROJECTS.ID; 

#EX5
SELECT COUNT( Employees.employee_id),department.name FROM Employees JOIN
 department ON department.department_id = Employees.employee_id GROUP BY department.department_id;

#EX6
SELECT Employees.name as employee_name,Employees.salary FROM Employees WHERE salary>50000;

#EX7
SELECT Attendance.Date,Attendance.Status FROM Attendance WHERE Attendance.employee_id=3;

#EX1
UPDATE Employees JOIN departments ON Employees.department_id=departments.department_id 
SET Employees.salary= Employees.salary *1.10 WHERE departments.name='HR';

SELECT Employees.name,Employees.salary FROM Employees JOIN departments ON Employees.department_id = departments.department_id
 WHERE departments.name='HR';
 
 #EX2
 UPDATE Employees SET department_id = (SELECT department_id FROM departments WHERE name = 'TESTING' LIMIT 1) WHERE department_id = 3 ;

SELECT Employees.name as employee_name, departments.name as dep_name FROM Employees JOIN departments ON Employees.department_id = departments.department_id 
WHERE departments.name = 'TESTING';

#EX3
DELETE FROM Projects WHERE name = 'NETWORK' ;

#EX4
ALTER TABLE Employees ADD COLUMN email varchar(50) UNIQUE; 

SELECT * FROM  Employees ;

#EX5
ALTER TABLE Employees ADD CHECK (Age>18);

SELECT * FROM  Employees ;

#EX6
ALTER TABLE Employees MODIFY gender VARCHAR(20) DEFAULT 'Unknown' ;




